### PR TITLE
Bump dex

### PR DESCRIPTION
**Pull request by jieyu**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

This improves the LDAP connector validation in Dex controller.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-64180

**Special notes for your reviewer**:

Konvoy e2e test with this branch can be tracked here:
https://github.com/mesosphere/konvoy/pull/1251

**Does this PR introduce a user-facing change?**:

```release-note
dex: improves the LDAP connector validation in Dex controller
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by makkes** [comment]
I re-triggered the check as I suspect it be an infra issue, judging from the logs.

**Comment by jieyu** [comment]
I think the CI of this repo has some issue. The e2e konvoy with this branch passed (all e2e passed)

**Comment by makkes** [comment]
@jieyu I'm looking into it

**Comment by hectorj2f** [comment]
@mhrabovcin @jieyu the test paniced https://teamcity.mesosphere.io/viewLog.html?buildId=2590221&buildTypeId=kubeaddons_KonvoyAddons&tab=buildLog&_focus=450

**Comment by makkes** [comment]
@shaneutt This is what I see when running the CI checks locally:
```

**Comment by makkes** [comment]
```
$ k -n kubeaddons get pods|grep traefik
traefik-kubeaddons-1.72.15-55fqr                     1/1     Running    0          5m21s
traefik-kubeaddons-6b846bb444-dwgwv                  0/1     Init:0/1   0          5m21s
traefik-kubeaddons-6b846bb444-rtdjw                  0/1     Init:0/1   0          5m21s
$ k -n kubeaddons describe pod traefik-kubeaddons-6b846bb444-dwgwv
[...]
  Warning  FailedMount  2m8s                 kubelet, e0698a00-d0fd-4974-a176-6bba5bf6e11f-control-plane  Unable to mount volumes for pod "traefik-kubeaddons-6b846bb444-dwgwv_kubeaddons(9a8d3f73-977a-4793-bca4-c3bfbf7db9b8)": timeout expired waiting for volumes to attach or mount for pod "kubeaddons"/"traefik-kubeaddons-6b846bb444-dwgwv". list of unmounted volumes=[ssl]. list of unattached volumes=[config ssl traefik-kubeaddons-token-xx5dx]
  Warning  FailedMount  1s (x10 over 4m10s)  kubelet, e0698a00-d0fd-4974-a176-6bba5bf6e11f-control-plane  MountVolume.SetUp failed for volume "ssl" : secret "traefik-kubeaddons-certificate" not found
```

**Comment by shaneutt** [comment]
I'm investigating the CI issues seen here, and will report back soon.

**Comment by shaneutt** [comment]
There was a problem in provisioning loadbalancers in the test cluster network. I added a patch for this which may resolve the CI issues we've seen.

**Comment by hectorj2f** [comment]
The patch should be done in a different PR because the CI issues are generic and not specific to this PR. I manually tested on my Konvoy cluster and it worked as expected.

**Comment by shaneutt** [comment]
> The patch should be done in a different PR because the CI issues are generic and not specific to this PR. I manually tested on my Konvoy cluster and it worked as expected.

I disagree. By that logic we should ignore and stop running our CI tests here, and simply test everything in Konvoy like we used to. We've only just started on the initiatives (like CI here) outlined in the [Addon CI Improvements](https://jira.d2iq.com/browse/D2IQ-61016) epic, I personally will not capitulate to undermining the work that has been done thus far and the work that still needs to be done by agreeing to force PRs that are failing CI through instead of taking the time to understand the failures and ensure we don't have bugs, and also inform the continued efforts of CI improvements throughout the ecosystem.

**Comment by hectorj2f** [comment]
To me it looks like the CI state isn't healthy so it should be fixed asap or PRs will get blocked as it was in this case.

Screen Shot 2020-02-19 at 3 27 25 PM

**Comment by shaneutt** [comment]
I'm actively digging into the problem to identify it and correct it asap, thank you.

**Comment by hectorj2f** [comment]
Thanks @shaneutt

**Comment by shaneutt** [comment]
The most recent failure suggests that networking was _not_ at the heart of the problem. I'm running a local manual deployment of the same environment to investigate and will report back asap.

**Comment by shaneutt** [comment]
I did notice that the general testing group has become somewhat overloaded (it works locally, but it's quite slow in TC) as such I've created the following JIRA to follow up and improve this so PRs can be resolved faster: https://jira.d2iq.com/browse/D2IQ-64455

**Comment by shaneutt** [comment]
I did notice that the general testing group has become somewhat overloaded (it works locally, but it's quite slow in TC) as such I've created the following JIRA to follow up and improve this so PRs can be resolved faster: https://jira.d2iq.com/browse/D2IQ-64455

**Pull request merged**
