### PR TITLE
chore: bump opsportal version

### PR DESCRIPTION
**Pull request by hectorj2f**
**What type of PR is this?**

Chore
**What this PR does/ why we need it**:

Bump opsportal so it uses the latest kommander ui and hopefully we align kommander ui for both OpsPortal and Kommander UI container.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
OpsPortal: bump kommander ui version fixing the service monitor issues
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by armandgrillet — APPROVED** [review]

**Comment by jimmidyson** [comment]
@hectorj2f failing check, from `https://teamcity.mesosphere.io/buildConfiguration/kubeaddons_KubernetesBaseAddons/3055587?showLog=3055587_719_719&logFilter=debug`:

```
panic: the revision for addons elasticsearch was not properly updated (current: 6.8.13-12, previous from branch master: 7.10.1-1). Please update the revision for any addons which you modify (see CONTRIBUTING.md)
```

**Comment by makkes** [comment]
> @hectorj2f failing check, from `https://teamcity.mesosphere.io/buildConfiguration/kubeaddons_KubernetesBaseAddons/3055587?showLog=3055587_719_719&logFilter=debug`:
> 
> ```
> panic: the revision for addons elasticsearch was not properly updated (current: 6.8.13-12, previous from branch master: 7.10.1-1). Please update the revision for any addons which you modify (see CONTRIBUTING.md)
> ```

The checker script is buggy in the sense that it always checks against `master` branch. I applied this patch locally:
```
$ git diff test/scripts/test-wrapper.go
diff --git a/test/scripts/test-wrapper.go b/test/scripts/test-wrapper.go
index 47fb6a8..73f104c 100644
--- a/test/scripts/test-wrapper.go
+++ b/test/scripts/test-wrapper.go
@@ -20,7 +20,7 @@ import (
 
 const (
        upstreamRemote = "origin"
-       upstreamBranch = "master"
+       upstreamBranch = "release/3.2"
 )
 
 type addonName string
@@ -79,7 +79,7 @@ func main() {
 func getModifiedAddons() ([]addonName, error) {
        addonsModifiedMap := make(map[addonName]struct{})
        stdout := new(bytes.Buffer)
-       cmd := exec.Command("git", "diff", "origin/master", "--name-only")
+       cmd := exec.Command("git", "diff", "origin/release/3.2", "--name-only")
        cmd.Stdout = stdout
        cmd.Stderr = os.Stderr
        if err := cmd.Run(); err != nil {
```
and re-ran the script:
```
$ go run -tags experimental scripts/test-wrapper.go
INFO: ensuring revision was updated for modified addon opsportal
INFO: addon opsportal has an updated revision 1.5.0-8 (upstream branch release/3.2: 1.5.0-5)
TestSsoGroup
TestPrometheusGroup
TestIstioGroup
```
So from my POV everything looks fine and we can just override the CI check.

@jimmidyson @hectorj2f @joejulian wdyt?

**Comment by hectorj2f** [comment]
yes, we need to move forward because it looks unrelated to me.

**Comment by makkes** [comment]
> @makkes since that patch would also fix any future backports to this branch, should we just include it?
> 
> We should probably do that every time we make a release branch.

yes: https://github.com/mesosphere/kubernetes-base-addons/pull/852

**Comment by hectorj2f** [comment]
Guys https://github.com/mesosphere/kubernetes-base-addons/pull/852 is not backported to release/3.2 ... can we merge this PR ?

**Pull request merged**
