### PR TITLE
[prometheus] Bump thanos to v0.17.1

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

chore

**What this PR does/ why we need it**:

upgrade thanos version (finally). bumped thanos (query) in kommander which upgraded to use v0.17.1 so doing the same here.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-73217

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
prometheus: Added new Thanos sidecar metrics
prometheus: Significantly improved Thanos sidecar latency (reduced ~2x)
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by samvantran — APPROVED** [review]

**Review by armandgrillet — APPROVED** [review]
LGTM.

**Comment by joejulian** [comment]
Please update (or mark none) the release note from the perspective of an end user deciding whether they need this upgrade.

**Comment by gracedo** [comment]
> Please update (or mark none) the release note from the perspective of an end user deciding whether they need this upgrade.

Something more than the current `prometheus: Upgrade thanos sidecar to v0.17.1` ?

**Comment by joejulian** [comment]
> > Please update (or mark none) the release note from the perspective of an end user deciding whether they need this upgrade.
> 
> Something more than the current `prometheus: Upgrade thanos sidecar to v0.17.1` ?

Yes. That has no meaning. This asks a busy admin to go research it for themselves. When I'm administering a thing and my vendor brings to me an upgrade, performing that upgrade increases risk and costs time, I want to know in one single document what value I'm getting out of it to know if it's worth it.

**Comment by gracedo** [comment]
> > > Please update (or mark none) the release note from the perspective of an end user deciding whether they need this upgrade.
> > 
> > 
> > Something more than the current `prometheus: Upgrade thanos sidecar to v0.17.1` ?
> 
> Yes. That has no meaning. This asks a busy admin to go research it for themselves. When I'm administering a thing and my vendor brings to me an upgrade, performing that upgrade increases risk and costs time, I want to know in one single document what value I'm getting out of it to know if it's worth it.

fixed

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/4

**Pull request merged**
