### PR TITLE
WIP: Using Cluster Claim Controller for KBA.

### PR DESCRIPTION
**Pull request by orsenthil**
### WIP - Using Cluster Claim Controller for KBA.

**What type of PR is this?**

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by joejulian** [comment]
Ooh, exciting!

**Comment by orsenthil** [comment]
It looks like Dispatch upgrade results in a failure. It's a dispatch bug/behavior. Continuing to investigate.

**Comment by shaneutt** [comment]
@orsenthil if there's any assistance you need to move this from WIP to ready, please let us know @mesosphere/sig-ksphere-catalog :vulcan_salute:

**Comment by orsenthil** [comment]
I will restart on this, as we have upgraded Dispatch and this PR was neglected for a long time.

**Pull request closed without merging**
