### PR TITLE
Added cluster-local-gateway to istio addon

### PR DESCRIPTION
**Pull request by Gilbert88**
Added cluster-local-gateway to istio addon. There is no behavior change. The cluster-local-gateway is turned off by default.

**What type of PR is this?**
Feature

**What this PR does/ why we need it**:
This PR added cluster-local-gateway to istio addon, so that services from knative serving can be queried internally within the cluster.

**Which issue(s) this PR fixes**:
[D2IQ-68381](https://jira.d2iq.com/browse/D2IQ-68381)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
No user change needed by default. Introduce a new option to turn on the cluster local gateway.
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by Gilbert88** [comment]
> @Gilbert88 what is the konvoy release with which you are planning to release Kubeflow?

The next one or two releases of kudo-kubeflow will base on Konvoy 1.4.2

**Comment by shaneutt** [comment]
@Gilbert88 & @GoelDeepak just double checking since this PR is getting stale: is there any assistance needed to move this one forward?

**Comment by GoelDeepak** [comment]
> @Gilbert88 & @GoelDeepak just double checking since this PR is getting stale: is there any assistance needed to move this one forward?

@shaneutt this was on hold because of the changes happening in underlying istio. I don't know why @joejulian removed the hold tag

**Comment by shaneutt** [comment]
@Gilbert88 checking in?

**Comment by GoelDeepak** [comment]
@shaneutt  I synced with @Gilbert88 and I'll be picking up this PR as it needs to be adjusted for new istio helm chart

**Comment by shaneutt** [comment]
@GoelDeepak are we still in a holding pattern here? Has anything changed?

**Comment by GoelDeepak** [comment]
@Gilbert88 I think this can be closed as you have this taken care as part of the Kubeflow itself. right?

**Pull request closed without merging**
