### PR TITLE
addons/metallb: bump metallb container images with security fixes

### PR DESCRIPTION
**Pull request by mhrabovcin**
JIRA(s):
- https://jira.mesosphere.com/browse/DCOS-62694
- https://jira.mesosphere.com/browse/DCOS-62733

Konvoy build:
- https://teamcity.mesosphere.io/viewLog.html?buildId=2545418&tab=queuedBuildOverviewTab

### CODE REVIEW

**Comment by shaneutt** [comment]
Just checking: are we not able to receive a chart update that would take care of this rather than tagging the components images specifically?

**Comment by GoelDeepak** [comment]
> Just checking: are we not able to receive a chart update that would take care of this rather than tagging the components images specifically?

@shaneutt The way I understood is that we are using the upstream chart for metallb which is still on 0.8.1. So we have two options - 1. either to bump the new image (the way it is done in this PR) 2. or update the upstream chart which may take sometime

**Comment by alejandroEsc** [comment]
@GoelDeepak  do we need this PR for GA?

**Comment by GoelDeepak** [comment]
> @GoelDeepak do we need this PR for GA?

Its say security fixes so I would guess the answer would be yes

**Pull request merged**
