### PR TITLE
chore: upgrade dex from v2.22.0 to v2.27.0

### PR DESCRIPTION
**Pull request by GoelDeepak**
**What type of PR is this?**
Chore

**What this PR does/ why we need it**:
Upgrade dex image from 2.22.0 to 2.27.0

**Which issue(s) this PR fixes**:
https://jira.d2iq.com/browse/D2IQ-73489

**Special notes for your reviewer**:
Validated the image by testing manually. Below are the two tests:
1. Tried fresh installation 
2. Tried upgrade from the previous installation

**Does this PR introduce a user-facing change?**:

```release-note
dex has been upgraded from 2.22.0 to 2.27.0
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by armandgrillet** [comment]
CI is failing due to `panic: the revision for addons dex was not properly updated (current: 2.22.0-12, previous from branch master: 2.22.0-12).`, I believe we need to update the annotations of `dex.yaml` to fix that.

**Comment by makkes** [comment]
@GoelDeepak I took the liberty to update your branch with the base branch. I hope you don't mind.

**Comment by GoelDeepak** [comment]
> @GoelDeepak I took the liberty to update your branch with the base branch. I hope you don't mind.

❤️ Thanks for taking care of it

**Review by makkes — APPROVED** [review]

**Review by joejulian — APPROVED** [review]

**Comment by joejulian** [comment]
@GoelDeepak Can you please [sign your commit](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/signing-commits)?

**Pull request merged**
