### PR TITLE
Added Dispatchfile that emulates the TC gating job

### PR DESCRIPTION
**Pull request by pcrews**
Adding a Dispatch file because we have to use our shiny new product

### CODE REVIEW

**Comment by joejulian** [comment]
@pcrews Would you mind adding a more verbose PR summary, please? I'd like the commit history to show the us from next year what we actually were thinking. :smile:

**Comment by shaneutt** [comment]
@pcrews this has been sitting in `WIP` and review for some time, is there any assistance we can provide to help move this towards `ready` state?

**Comment by shaneutt** [comment]
It looks like pcrews is deactivated as a user in the org, so closing this for the time being.

**Pull request closed without merging**
