### PR TITLE
chore(dex, dka): support kubectl token plugin

### PR DESCRIPTION
**Pull request by jr0d**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

* adds hmac_secret default value
* bumps dka image
* bumps dka initContainer image
* adds additional redirect URL to dex config

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-65269

**Special notes for your reviewer**:
changes commits: https://github.com/mesosphere/kubernetes-base-addons/pull/193/commits/dc48b05eea61081481110f542aef57f05cd938ec, https://github.com/mesosphere/kubernetes-base-addons/pull/193/commits/1583e71512aa2a926c87b78a3c51fe7f2c787d9f

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by jieyu** [comment]
@jr0d FYI, i triggered an konvoy e2e run with this PR to run konvoy aws e2e tests with this KBA branch.

**Comment by jr0d** [comment]
@shaneutt I've done quite a bit of testing with this build. I'll trigger konvoy e2e one last time and report back.

**Comment by jr0d** [comment]
@shaneutt aws and docker e2e test have passed: https://teamcity.mesosphere.io/viewLog.html?buildId=2682191&tab=buildResultsDiv&buildTypeId=ClosedSource_MkeLite_MkeLiteE2e

**Comment by shaneutt** [comment]
LGTM once CI is ready

**Comment by shaneutt** [comment]
The konvoy failures seen here are [due to an upstream konvoy issue](https://jira.d2iq.com/browse/D2IQ-66128)

**Pull request merged**
