### PR TITLE
[prometheus] bump to chart containing elasticsearch alertmanager rules

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

Allows the creation of elasticsearch rules to fire in alertmanager 

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-76519

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
prometheus: possible to enable elasticsearch rules 
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by gracedo — COMMENTED** [review]
need an update to values annotation otherwise lgtm

**Comment by alejandroEsc** [comment]
> need an update to values annotation otherwise lgtm

Sorry which ones?

**Comment by alejandroEsc** [comment]
@mesosphere-mergebot backport release/4.1

**Comment by branden** [comment]
I think we need to update the `values.chart.helm.kubeaddons.mesosphere.io/prometheus` annotation since the chart bump brings a different set of default values. Otherwise LGTM.

**Comment by alejandroEsc** [comment]
> I think we need to update the `values.chart.helm.kubeaddons.mesosphere.io/prometheus` annotation since the chart bump brings a different set of default values. Otherwise LGTM.

OHHH sorry! good point, ok will do.

**Review by gracedo — APPROVED** [review]

**Review by branden — APPROVED** [review]

**Comment by alejandroEsc** [comment]
Backport PR for release/4

**Comment by alejandroEsc** [comment]
@mesosphere-mergebot backport release/4

**Pull request merged**
