### PR TITLE
prometheus: Enable etcd rules

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

bug

**What this PR does/ why we need it**:

When I removed mesosphere-specific etcd rules to use the default, I didn't realize the config here needed to be updated to reflect those changes. I tested adding the rule to the daily cluster and verified all the rules look good.
image
The change was made in v9.3.4, so we need to backport this to konvoy 1.7/1.6/1.5 (release/3.3, release/3.0, release/2.5)

Also, removed some unnecessary configs that have since been added to the chart values as default (https://github.com/mesosphere/charts/pull/969, https://github.com/mesosphere/charts/pull/962/files#diff-4eefbe60d75fc0250847e2e4dfd675f9977d572e6f0b5615b552b8223719a6caR2324)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
prometheus(fix): Re-enable etcd prometheus rules
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by s12chung — APPROVED** [review]

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/3.3

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/3.0

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/2.5

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/3.0

**Review by joejulian — APPROVED** [review]

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/2 pleaseee

**Review by alejandroEsc — APPROVED** [review]
interesting, lgtm.

**Pull request merged**
