### PR TITLE
chore(opsportal): bump to 0.3.16

### PR DESCRIPTION
**Pull request by TattdCodeMonkey**
**What type of PR is this?**
Bump

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by jaxesn** [comment]
Is this one we should patch into the testing tag that will go out with 1.5? I am thinking it probably is...

**Comment by TattdCodeMonkey** [comment]
@joejulian added a line about the ui bump. the previous version before this was 3.85.0, and this updates it to 3.100.0 via the chart, but there were no user facing changes to konvoy ui in those version, this is just to keep it in sync with the kommander version.

**Comment by juliangieseke** [comment]
@TattdCodeMonkey not exactly correct, there is a bugfix in this bump that needs to be in 1.5. (removing kommander links in case kommander is not installed)

@jaxesn yes

theres a couple things that need to improve:
1. we dont have changelogs for the chart, so even if a team provides a changelog for their component, it is very likely incomplete. 
2. we have that info in JIRA (even tho its badly maintained too) and generally speaking JIRA is our source of truth in this company. 
3. if we'd have multi component addons, we would be able to skip these shell-charts and provide way more accurate release notes, but thats not in place too…
4. if we'd have konvoy fetching latest version of addons on `init` in place, our need to get certain things into certain versions would be less bad

overall, there is multiple things that are incomplete/badly maintained currently, but blocking such PRs here will put features and releases at risk. :( 

dont get me wrong, I'm not saying you should stop asking for release notes, its more raising that there is lots of things that we need to improve in order to be able to fulfill your ask.

**Comment by juliangieseke** [comment]
all the above said, CI is red for unrelated reasons: 
```
TestPrometheusGroup: addons.go:103: STATUS: waiting for addons: map[prometheusadapter:0xc000502a80]
19:01:05
      TestPrometheusGroup: addons.go:103: STATUS: waiting for addons: map[prometheusadapter:0xc000502a80]
19:03:05
      TestPrometheusGroup: addons.go:103: STATUS: waiting for addons: map[prometheusadapter:0xc000502a80]
19:05:06
      TestPrometheusGroup: addons.go:103: STATUS: waiting for addons: map[prometheusadapter:0xc000502a80]
19:07:06
      TestPrometheusGroup: addons.go:103: STATUS: waiting for addons: map[prometheusadapter:0xc000502a80]
19:09:06
      TestPrometheusGroup: addons.go:103: STATUS: waiting for addons: map[prometheusadapter:0xc000502a80]
19:09:33
      TestPrometheusGroup: addons.go:123: addon prometheusadapter did not provision. Status: &{Ready:false Stage:}
```
is that a known thing? there were some hiccups lately with CI

**Comment by juliangieseke** [comment]
hm, @jaxesn @joejulian there is one more KBA release on june 11th, isnt that the one we'll use in konvoy 1.5.0 stable? we will have a couple more bug fixes that we'll want to have in 1.5 🤷

**Pull request merged**
