### PR TITLE
prometheus: set nameOverride to preserve previous Service name

### PR DESCRIPTION
**Pull request by dkoshkin**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

Following the [chart recommendation](https://github.com/mesosphere/charts/tree/master/staging/prometheus-operator#zero-downtime) setting `nameOverride` for the Prometheus addon.

Also reverted the changes back to the old service.

Cluster with this version
```
Run `konvoy apply kubeconfig` to update kubectl credentials.

Navigate to the URL below to access various services running in the cluster.
  https://a45c58c39b0c64dcdb9193df5f0d6fa4-1473442938.us-west-2.elb.amazonaws.com/ops/landing
And login using the credentials below.
  Username: eloquent_mclean
  Password: O7C1tyooQbiLMRu7D1VyPWy0IVKOm6n9N9DAxPJlNE2IPiqwJcSQS7JdpAkJdVPp

If the cluster was recently created, the dashboard and services may take a few minutes to be accessible.
```

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Prometheus: preserve the name `prometheus-operator` to avoid breaking any Prometheus metrics clients.
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by branden** [comment]
+1 using `nameOverride` to use the old name, thanks for catching that. When I last changed the release name that broke the nightly test, so I'll run it against this PR just to be certain.

**Review by branden — APPROVED** [review]

**Review by gracedo — APPROVED** [review]

**Comment by branden** [comment]
Nightly job failed, looks like a metrics test needs a tweak: https://teamcity.mesosphere.io/buildConfiguration/kubeaddons_Nightly_KubernetesBaseAddonsNightlt/3138127?buildTab=log&expandAll=true&focusLine=13628

```
      harness.go:73: ERROR:   []test.PrometheusUpMetric{
12:11:30
              {Name: "up", Job: "kubernetes-nodes-containerd"},
12:11:30
              {Name: "up", Namespace: "default", Service: "kubernetes", Job: "apiserver"},
12:11:30
              {Name: "up", Namespace: "kube-system", Job: "kubernetes-calico-node"},
12:11:30
          -   {
12:11:30
          -     Name:      "up",
12:11:30
          -     Namespace: "kube-system",
12:11:30
          -     Service:   "prometheus-kubeaddons-kube-kubelet",
12:11:30
          -     Job:       "kubelet",
12:11:30
          -   },
12:11:30
              {Name: "up", Namespace: "kube-system", Service: "prometheus-kubeaddons-prom-coredns", Job: "coredns"},
12:11:30
              {Name: "up", Namespace: "kube-system", Service: "prometheus-kubeaddons-prom-kube-proxy", Job: "kube-proxy"},
12:11:30
              ... // 4 identical elements
12:11:30
              {Name: "up", Namespace: "kubeaddons", Service: "opsportal", Job: "opsportal"},
12:11:30
              {Name: "up", Namespace: "kubeaddons", Service: "prometheus-kubeaddons-grafana", Job: "prometheus-kubeaddons-grafana"},
12:11:30
          -   {
12:11:30
          -     Name:      "up",
12:11:30
          -     Namespace: "kubeaddons",
12:11:30
          -     Service:   "prometheus-kubeaddons-kube-state-metrics",
12:11:30
          -     Job:       "kube-state-metrics",
12:11:30
          -   },
12:11:30
              {Name: "up", Namespace: "kubeaddons", Service: "prometheus-kubeaddons-prom-alertmanager", Job: "prometheus-kubeaddons-prom-alertmanager"},
12:11:30
              {Name: "up", Namespace: "kubeaddons", Service: "prometheus-kubeaddons-prom-operator", Job: "prometheus-kubeaddons-prom-operator"},
12:11:30
              {Name: "up", Namespace: "kubeaddons", Service: "prometheus-kubeaddons-prom-prometheus", Job: "prometheus-kubeaddons-prom-prometheus"},
12:11:30
          +   {
12:11:30
          +     Name:      "up",
12:11:30
          +     Namespace: "kubeaddons",
12:11:30
          +     Service:   "prometheus-kubeaddons-prom-state-metrics",
12:11:30
          +     Job:       "kube-state-metrics",
12:11:30
          +   },
12:11:30
              {Name: "up", Namespace: "kubeaddons", Service: "prometheus-kubeaddons-prometheus-node-exporter", Job: "node-exporter"},
12:11:30
              {Name: "up", Namespace: "kubeaddons", Service: "traefik-kubeaddons-prometheus", Job: "traefik-kubeaddons-prometheus"},
12:11:30
              {Name: "up", Namespace: "velero", Service: "velero-kubeaddons", Job: "velero-kubeaddons"},
12:11:30
            }
```

**Review by branden — APPROVED** [review]

**Comment by branden** [comment]
This run of the nightly job against the PR failed only due to a race caused by the fact that it wasn't run against master: https://teamcity.mesosphere.io/buildConfiguration/kubeaddons_Nightly_KubernetesBaseAddonsNightlt/3139644?showLog=3139644_13591_497.13991&logFilter=debug

Runs of the nightly test job against master don't execute upgrade tests. Because this run upgraded prometheus from the version on master, it caught an unexpected `up` metric for a service from the previous version, recorded while it was deployed. This failure doesn't reflect a problem with the PR, so this is good to merge.

**Comment by branden** [comment]
@mesosphere-mergebot backport release/3 release/4

**Pull request merged**
