### PR TITLE
kibana: Downgrade to 6.8.10 to fix regression

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**

bug

**What this PR does/ why we need it**:

downgrade to 6.8.10 to fix regression - metrics were not getting exported

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-73949

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: Downgrade kibana and elasticsearch to 6.8.10 to fix a regression
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]

**Review by hectorj2f — COMMENTED** [review]
I am wondering if there would be any issue with ES being 6.8.13. I believe it won't.

**Comment by gracedo** [comment]
> I am wondering if there would be any issue with ES being 6.8.13. I believe it won't.

oh good point, I remember @alejandroEsc having to match the versions. I would expect the tests to fail if not compatible though, and they're passing here. will wait for @alejandroEsc to approve

**Comment by alejandroEsc** [comment]
> > I am wondering if there would be any issue with ES being 6.8.13. I believe it won't.
> 
> oh good point, I remember @alejandroEsc having to match the versions. I would expect the tests to fail if not compatible though, and they're passing here. will wait for @alejandroEsc to approve

Kibana will always complain if mismatch. So expect lots of logs.

**Comment by gracedo** [comment]
> > > I am wondering if there would be any issue with ES being 6.8.13. I believe it won't.
> > 
> > 
> > oh good point, I remember @alejandroEsc having to match the versions. I would expect the tests to fail if not compatible though, and they're passing here. will wait for @alejandroEsc to approve
> 
> Kibana will always complain if mismatch. So expect lots of logs.

to be safe I'll change ES to match :)

**Review by samvantran — APPROVED** [review]

**Review by branden — APPROVED** [review]

**Pull request merged**
