### PR TITLE
[tests] [flagger] [kiali] Update references to prometheus resources

### PR DESCRIPTION
**Pull request by branden**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

This updates some lingering references to Prometheus resources that were changed with https://github.com/mesosphere/kubernetes-base-addons/pull/1129. 

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-75500

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [x] The core changes are covered by tests.
* [x] The documentation is updated where needed.

### CODE REVIEW

**Comment by branden** [comment]
Nightly tests pass against this branch: https://teamcity.mesosphere.io/buildConfiguration/kubeaddons_Nightly_KubernetesBaseAddonsNightlt/3124733?focusLine=0

I'm not sure why the test-install and test-upgrade checks are failing. Both their logs end like this:

```
2021-05-18T18:31:58.701398245Z INFO: ensuring revision was updated for modified addon flagger
2021-05-18T18:31:59.144483995Z INFO: addon flagger has an updated revision 0.19.0-5 (upstream branch master: 0.19.0-4)
2021-05-18T18:31:59.144514152Z INFO: ensuring revision was updated for modified addon kiali
2021-05-18T18:31:59.443171229Z INFO: addon kiali has an updated revision 1.29.1-3 (upstream branch master: 1.29.1-2)
2021-05-18T18:32:00.876419683Z + tests=
2021-05-18T18:32:00.876791007Z make: *** [Makefile:113: dispatch-test-install-upgrade] Error 1
```
Is this an error in `test/dispatch_test_install_upgrade.sh`?

**Review by joejulian — APPROVED** [review]

**Review by samvantran — APPROVED** [review]
do these changes need to be captured in a patch file in m/charts at all?

**Comment by branden** [comment]
There are no changes to charts with this PR, so there's nothing to capture in a chart patch.

**Comment by branden** [comment]
@mesosphere-mergebot backport release/3 release/4

**Pull request merged**
