### PR TITLE
[fluent-bit] Replace dots with underscores in audit logs

### PR DESCRIPTION
**Pull request by branden**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

Audit logs may include resource labels, which may include dots (`.`). Elasticsearch treats dots as field delimiters when parsing incoming records, which can lead to conflicts when assembling the final record to store, causing it to be rejected. This PR reduces the number of dropped audit logs by replacing all periods with underscores in audit log records that are sent to Elasticsearch.

A couple screenshots to demonstrate the impact of this change on a running cluster:

Screen Shot 2021-01-20 at 6 26 27 PM

Screen Shot 2021-01-20 at 6 25 51 PM

**Which issue(s) this PR fixes**:

* https://jira.d2iq.com/browse/D2IQ-73839

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
\[fluent-bit\] Fixes an issue causing some audit logs to be dropped.
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [x] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [x] The documentation is updated where needed.

### CODE REVIEW

**Review by s12chung — APPROVED** [review]

**Review by gracedo — APPROVED** [review]

**Review by sebbrandt87 — CHANGES_REQUESTED** [review]
wait, let me check if we should also solve this with the filter we added to general logs.
As this change isn't good in my opinion.

**Comment by alejandroEsc** [comment]
could we wait until after merging kibnana 7.9.3 please?

**Review by sebbrandt87 — COMMENTED** [review]
unblock, but we might add more changes as discussed

**Comment by sebbrandt87** [comment]
@branden yes :)
I just thought we add here the elasticsearch index_template changes that are might needed as well. But also I am okay with it being merged like it is now.

**Comment by branden** [comment]
Ah sorry for the confusion @sebbrandt87. I know we discussed checking the audit log index template to see if it needs updates, but I saw that as a separate follow-on task. I want to get this PR merged as soon as possible because it solves a customer issue without (AFAICT) introducing new problems. Sounds like you're cool with this being merged as-is but LMK if you think we need to revert. I'll set up a meeting for us to review the template once the current release frenzy is over. Here's a ticket for tracking: https://jira.d2iq.com/browse/D2IQ-73958

**Pull request merged**
