### PR TITLE
feat: bump Ambassador to v6.7.5

### PR DESCRIPTION
**Pull request by dkoshkin**
**What type of PR is this?**

Feature

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-75533

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- Update Ambassador to v6.7.5
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]

**Review by GoelDeepak — APPROVED** [review]

**Comment by dkoshkin** [comment]
Hmm looks like the upgrade fails here 🤔 
Although I tried an upgrade in KBA from `testing-1.20-4.0.0-rc.3` > `testing-1.20-4.0.0-rc.3` and it worked fine.

```
NAMESPACE   NAME                                                                   READY   STAGE      REVISION
            clusteraddon.kubeaddons.mesosphere.io/ambassador                       true    deployed   1.13.3-1
```

**Review by gracedo — APPROVED** [review]
Should we include the CVE this bump mitigates in the release notes?

**Comment by alejandroEsc** [comment]
We are removing this addon here: https://github.com/mesosphere/kubernetes-base-addons/pull/1105 is this ok?

**Comment by joejulian** [comment]
Please, let's discuss https://github.com/mesosphere/kubernetes-base-addons/pull/1105 and see if we can just eliminate this maintenance burden.

**Comment by joejulian** [comment]
@mesosphere-mergebot backport release/4

**Pull request merged**
