### PR TITLE
[release/3][BACKPORT] prometheus: Enable etcd rules

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
This is a backport of the following PR:

https://github.com/mesosphere/kubernetes-base-addons/pull/938

**What type of PR is this?**

bug

**What this PR does/ why we need it**:

When I removed mesosphere-specific etcd rules to use the default, I didn't realize the config here needed to be updated to reflect those changes. I tested adding the rule to the daily cluster and verified all the rules look good.
image
The change was made in v9.3.4, so we need to backport this to konvoy 1.7/1.6/1.5 (release/3.3, release/3.0, release/2.5)

Also, removed some unnecessary configs that have since been added to the chart values as default (https://github.com/mesosphere/charts/pull/969, https://github.com/mesosphere/charts/pull/962/files#diff-4eefbe60d75fc0250847e2e4dfd675f9977d572e6f0b5615b552b8223719a6caR2324)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
prometheus(fix): Re-enable etcd prometheus rules
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by gracedo — APPROVED** [review]

**Review by joejulian — APPROVED** [review]

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/2 pleaseee 🙏

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/2

**Comment by alejandroEsc** [comment]
in this backport will `Kubernetes Base Addons (sig-ksphere-catalog) ` pass? It is testing against master i think?

**Comment by gracedo** [comment]
> in this backport will `Kubernetes Base Addons (sig-ksphere-catalog) ` pass? It is testing against master i think?

yeah.. I'm not sure backport prs will test CI 🤔 
`panic: the revision for addons jaeger was not properly updated (current: 2.18.3-5, previous from branch master: 2.18.3-6). Please update the revision for any addons which you modify (see CONTRIBUTING.md)
12:49:31`

**Review by joejulian — APPROVED** [review]

**Comment by armandgrillet** [comment]
Auto-merging this is blocked due to unsigned mergebot commits, I've raised the issue in https://mesosphere.slack.com/archives/C5U03P5T6/p1615530702043100

**Comment by gracedo** [comment]
@joejulian the mergebot commits aren't signed, it might be easier to just open up a new pr and reapply the changes, I'll do that now

**Comment by gracedo** [comment]
Using https://github.com/mesosphere/kubernetes-base-addons/pull/981 instead

**Pull request closed without merging**
