### PR TITLE
release: stable-2.0.0

### PR DESCRIPTION
**Pull request by joejulian**
Release of stable-2.0.0

### CODE REVIEW

**Comment by jimmidyson** [comment]
This is a 2.0.0 - I assume from the new major version that there are backwards compatibility issues. Will this affect upgrades?

**Comment by joejulian** [comment]
@jimmidyson Good point. That should be noted in the release notes. I'll update that.

The answer is, yes, but only for istio. Since it's in preview, product was comfortable with that.

**Comment by GoelDeepak** [comment]
Blocking it till we have final solution for istio because of the limitation in KUDO there is a decision to try helm based approach.

**Comment by joejulian** [comment]
Due to the above and the limited successful soak time, closing.

**Pull request closed without merging**
