### PR TITLE
feat: update kommander to 1.173.2

### PR DESCRIPTION
**Pull request by juliangieseke**

### CODE REVIEW

**Comment by juliangieseke** [comment]
@shaneutt @joejulian are we asked to wait for your reviews here or is it okay for us to admin-merge? 🤔

**Comment by alejandroEsc** [comment]
@juliangieseke sorry but admin-merge is not ok. Please do ping them on slack if needed.

**Comment by jaxesn** [comment]
I tested this version on beta9 and it looks good. Id like to get this merged and the beta9 tag retagged to include it.  I think tho, based on the conversation in slack, this should be removing the old version along with adding the new version.

**Comment by juliangieseke** [comment]
https://github.com/mesosphere/charts/pull/333 got merged which means we need a new PR in this repo, would love to get this one merged ASAP 🙇 cc @shaneutt @joejulian

**Comment by gracedo** [comment]
mesosphere/charts#333 looks like it would include my kommander chart changes (https://github.com/mesosphere/charts/pull/327) so I'll avoid making an interim bump in this repo and let it get taken care of in the followup PR once this one's merged. Does that make sense?

**Pull request merged**
