### PR TITLE
[dex, tfa] allow ops-portal landing page to regenerate username/password

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**

Bug 
**What this PR does/ why we need it**:

This allows a controlled refresh of secrets for dex and tfa, so the chain works like the following:

opsportal-credentials secret gets update
dex must update its configurations and so reloader triggers a new deployment which creates a new configmap
tfa needs a new configuration to pick up the dex changes so reloader checks the configmap from dex and triggers a new deployment

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-63608
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [X] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [X] The core changes are covered by tests.
* [X] The documentation is updated where needed.

### CODE REVIEW

**Comment by shaneutt** [comment]
Still wip? or ready now?

**Comment by alejandroEsc** [comment]
testing this again, note that opsportal had an issue that kept me from making progress but had nothing to do with my changes.

**Comment by alejandroEsc** [comment]
#Tests conducted:
- [X] Deploy konvoy pointing to this branch. Delete opsportal, reinstall. Works and passwords updated!
-

**Comment by joejulian** [comment]
1 commit? /grumble

**Comment by alejandroEsc** [comment]
```diff addons/dex/2.17.x/dex-1.yaml addons/dex/2.17.x/dex-2.yaml
10c10
<     catalog.kubeaddons.mesosphere.io/addon-revision: "2.17.0-1"
---
>     catalog.kubeaddons.mesosphere.io/addon-revision: "2.17.0-2"
47c47
<         secret.reloader.stakater.com/reload: "traefik-kubeaddons-certificate"
---
>         secret.reloader.stakater.com/reload: "traefik-kubeaddons-certificate,ops-portal-credentials"
```

```
$ diff addons/traefik-forward-auth/1.0.x/traefik-forward-auth-1.yaml addons/traefik-forward-auth/1.0.x/traefik-forward-auth-2.yaml
8c8
<     catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.4-1"
---
>     catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.4-2"
69c69
<         secret.reloader.stakater.com/reload: "traefik-kubeaddons-certificate"
---
>         secret.reloader.stakater.com/reload: "traefik-kubeaddons-certificate,dex-kubeaddons"
```

**Pull request merged**
