### PR TITLE
prometheus-operator: Upgrade chart

### PR DESCRIPTION
**Pull request by gracedo**
**What type of PR is this?**
Chore

**What this PR does/ why we need it**:
Upgrades our prometheus-operator fork to the latest official version (actual upgrade done in https://github.com/mesosphere/charts/pull/421, this is just bumping)

**Which issue(s) this PR fixes**:
https://jira.d2iq.com/browse/D2IQ-63553

**Special notes for your reviewer**:
Blocked on https://github.com/mesosphere/charts/pull/421. Once that is merged, I will point this chart back to mesosphere hosted chart

**Does this PR introduce a user-facing change?**:

```release-note
Upgrade prometheus-operator chart to v8.7.1.
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by shaneutt** [comment]
Let us know if there's anything that @mesosphere/sig-ksphere-catalog can do to help you with this @gracedo to get it unblocked and to `ready` state!

**Comment by gracedo** [comment]
@shaneutt just waiting for reviews on https://github.com/mesosphere/charts/pull/421 !

**Comment by joejulian** [comment]
This is timing out consistently in CI, doesn't look like this is a flake.

**Comment by shaneutt** [comment]
@gracedo let @mesosphere/sig-ksphere-catalog know if you need any help getting the CI issues squared away. In the current early stages of our addon CI code often the best way to diagnose the issues is to run the tests locally and investigate the cluster in realtime to find which components failed. Feel free to check in with us in [slack](https://app.slack.com/client/T0252D4NY/CLETZF5U6) too if you need help!

**Comment by makkes** [comment]
I refreshed the branch as we fixed a recent CI issue today. Hope that CI succeeds now.

**Pull request merged**
