### PR TITLE
bump all kubeaddons-addon-initializer

### PR DESCRIPTION
**Pull request by joejulian**
**What type of PR is this?**

**What this PR does/ why we need it**:

Update all init containers to use the same version

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by joejulian** [comment]
I think this upgrade test is broken. I've upgraded from v4.1.0 several times successfully.

**Review by gracedo — APPROVED** [review]

**Comment by joejulian** [comment]
@mesosphere-mergebot backport release/4

**Pull request merged**
