### PR TITLE
Bump prometheus-operator chart version

### PR DESCRIPTION
**Pull request by branden**
**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

This PR bumps the prometheus-operator chart version to pull in some upstream fixes. See https://github.com/mesosphere/charts/pull/619.

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-67910

**Special notes for your reviewer**:

I tested this PR by deploying Konvoy 1.15 with the KBA configversion set to this PR's branch, and observed that metrics appear in Grafana and Alertmanager fires the watchdog alert. I also verified that Grafana, Prometheus, and Alertmanager report that they're at the expected versions.

**Does this PR introduce a user-facing change?**:

```release-note
\[prometheus-operator\] Upgrade to version [0.38.1](https://github.com/coreos/prometheus-operator/releases/tag/v0.38.1)
\[prometheus\] Upgrade to version [2.17.2](https://github.com/prometheus/prometheus/releases/tag/v2.17.2)
\[grafana\] Upgrade to version [6.7.3](https://github.com/grafana/grafana/releases/tag/v6.7.3)
```

**Checklist**

* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [x] The relevant subset of integration tests pass locally.
* [x] The core changes are covered by tests.
* [x] The documentation is updated where needed.

### CODE REVIEW

**Comment by branden** [comment]
The e2e failure is a flake, I'll put together a ticket for the override.

**Comment by branden** [comment]
Here's the ticket for the e2e flake: https://jira.d2iq.com/browse/D2IQ-69192

**Comment by branden** [comment]
Looking into the integration test failure. It looks like Prometheus et. al. deploy and pass their tests, but prometheusadapter takes too long to deploy.

**Comment by joejulian** [comment]
No, this isn't a flake. There's a bug happening:
```
  		... // 12 identical lines
  		"    cpu:",
  		"      containerLabel: container",
- 		"      containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)",
- 		"      nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[2m])) by (<<.GroupBy>>)",
+ 		"      containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[2m]))",
+ 		"        by (<<.GroupBy>>)",
+ 		"      nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[2m]))",
+ 		"        by (<<.GroupBy>>)",
  		"      resources:",
  		"        overrides:",
  		... // 6 identical lines
  		"    memory:",
  		"      containerLabel: container",
- 		"      containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>}) by (<<.GroupBy>>)",
- 		"      nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)",
+ 		"      containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>})",
+ 		"        by (<<.GroupBy>>)",
+ 		"      nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'})",
+ 		"        by (<<.GroupBy>>)",
  		"      resources:",
  		"        overrides:",
  		... // 8 identical lines
```

That newline is making the values not match, so the controller continually thinks it needs updated.

**Comment by joejulian** [comment]
helm is outputting the values with lines wrapped - similar to the output generated by yq - so this seems to be standard. The values that are being compared to determine whether or not the addon needs updated do not have wrapped lines. This error is not caused by this PR so I'm going to merge this.

**Pull request merged**
