### PR TITLE
Automated chart bump elasticsearch-1.32.5

### PR DESCRIPTION
**Pull request by d2iq-dispatch**

### CODE REVIEW

**Review by makkes — APPROVED** [review]

**Comment by makkes** [comment]
The manifest is edited in-place. I don't know whether that is expected. Maybe someone else from @mesosphere/sig-ksphere-catalog can shed some light on this.

**Review by shaneutt — APPROVED** [review]

**Comment by makkes** [comment]
CI is failing consistently:
```
E0918 09:57:36.734135   11968 portforward.go:400] an error occurred forwarding 9000 -> 5601: error forwarding port 5601 to pod 1753e3bb950801a4fe04fedb0b4360da4d3396a90bb8d5ee04791b20ecd1edcc, uid : failed to execute portforward in network namespace "/var/run/netns/cni-f9b20dd4-1184-f7c6-8c18-8b79fed71e65": failed to dial 5601: dial tcp4 127.0.0.1:5601: connect: connection refused
```
https://teamcity.mesosphere.io/viewLog.html?buildTypeId=kubeaddons_KubernetesBaseAddons&buildId=2873467&tab=buildLog&logTab=tree&filter=debug&expand=all&_focus=924

**Comment by makkes** [comment]
@shaneutt TC integration tests are constantly failing. This is the error in the last build:
```
harness.go:63: had to recover in default test plan: runtime error: invalid memory address or nil pointer dereference
```
https://teamcity.mesosphere.io/viewLog.html?buildTypeId=kubeaddons_KubernetesBaseAddons&buildId=2923151&tab=buildLog&logTab=tree&filter=debug&expand=all&_focus=965

Do you have a hunch what's wrong here?

**Comment by shaneutt** [comment]
> @shaneutt TC integration tests are constantly failing. This is the error in the last build:
> ```
> harness.go:63: had to recover in default test plan: runtime error: invalid memory address or nil pointer dereference
> ```
> https://teamcity.mesosphere.io/viewLog.html?buildTypeId=kubeaddons_KubernetesBaseAddons&buildId=2923151&tab=buildLog&logTab=tree&filter=debug&expand=all&_focus=965
> 
> Do you have a hunch what's wrong here?

I'll take a look.

**Comment by shaneutt** [comment]
> > @shaneutt TC integration tests are constantly failing. This is the error in the last build:
> > ```
> > harness.go:63: had to recover in default test plan: runtime error: invalid memory address or nil pointer dereference
> > ```
> > 
> > 
> > https://teamcity.mesosphere.io/viewLog.html?buildTypeId=kubeaddons_KubernetesBaseAddons&buildId=2923151&tab=buildLog&logTab=tree&filter=debug&expand=all&_focus=965
> > Do you have a hunch what's wrong here?
> 
> I'll take a look.

The upgrade test is failing, for one thing:

```
      harness.go:71: ERROR: addon elasticsearch using the previous version '6.8.2-7' did not come up healthy
```

It expects to be able to deploy the previous version of the addon, the intention is to ensure downgrade support as well as upgrade.

This upgrade testing functionality was recently added: it may be the case that for elasticsearch the procedure would not work as it would for other addons.

The best thing would be for someone to test deploying the new addon and then replacing the current one with the previous one, followed by updating back to the newest changes. During the replacement/downgrade determine why deployment fails.

We should attempt to make elasticsearch downgradable to the previous revision if the cost to do so is reasonable, otherwise we may need to modify how we test elasticsearch.

**Comment by samvantran** [comment]
This is a bump to the last version of a deprecated elasticsearch chart. we also merged this version in the past and it bit us in upgrade and we had to revert https://github.com/mesosphere/kubernetes-base-addons/pull/512

closing this PR.

**Pull request closed without merging**
