### PR TITLE
Automated chart bump kubernetes-dashboard-3.0.2

### PR DESCRIPTION
**Pull request by d2iq-dispatch**
Add release note or "none":
```release-note
Bump Kubernetes Dashboard to 3.0.2
```

### CODE REVIEW

**Comment by alejandroEsc** [comment]
this is a major version bump, we should probably investigate it first.

**Comment by makkes** [comment]
rebased on top of master.

**Comment by makkes** [comment]
I tested this PR manually on a Konvoy 1.7.0 cluster and the dashboard works fine. From the [dashboard changelog](https://github.com/kubernetes/dashboard/releases) it looks like there's no real braking changes in it except for this one in 2.1.0: 

> Update Kubernetes dependencies to support v1.20 #5708

So from my perspective it's safe to merge this.

**Review by makkes — APPROVED** [review]

**Comment by alejandroEsc** [comment]
@makkes thank you for ensuring that it does deploy properly. Major revision changes should probably be managed by an ack of product? I am not sure. But I am ok with merging this in.

**Review by alejandroEsc — APPROVED** [review]
lgtm

**Pull request merged**
