### PR TITLE
Decreased curator days to 10 and set the ES data node disk size to 50Gi

### PR DESCRIPTION
**Pull request by vrejabram**
**What type of PR is this?**
Bug

**What this PR does/ why we need it**:
Decreased the Curator delete_indices action days to 10 and set the ElasticSearch data node disk size to 50Gi -- https://jira.d2iq.com/browse/D2IQ-65315

**Which issue(s) this PR fixes**:
https://jira.d2iq.com/browse/D2IQ-65315

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Checklist**
* [x] The commit message explains the changes and why are needed.
* [x] The code builds and passes lint/style checks locally.
* [x] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [x] The documentation is updated where needed.

### CODE REVIEW

**Comment by aayvazyan** [comment]
@shaneutt These changes are result of soaking and our experience on the soak clusters. It turned out that the current `default` value for the curator indices rotation and Elasticsearch volume size are not sufficient and we were getting alerted on the aws soak. So on soak we decreased `unit_count ` to `10 days`, which means indices older than 10 days will be removed, and we also increased Elastisearch volume size from `30Gi` to `50Gi`,  as 30G was not enough even to keep indices for the last 10 days. 

#### Slack conversations
[Conversation for the curator](https://mesosphere.slack.com/archives/CPF8FQ4PN/p1582488575010300)
[Conversation for the Elasticsearch volume size](https://mesosphere.slack.com/archives/CPF8FQ4PN/p1583299687080600)

#### Related Tickets
https://jira.d2iq.com/browse/D2IQ-65315
https://jira.d2iq.com/browse/D2IQ-64653

**Comment by shaneutt** [comment]
Excellent context add, thank you :+1: 
This LGTM, the only thing left is we need to create revisions for the addons we've updated here, let me know if you need any help with that and [see the documentation here](https://github.com/mesosphere/kubernetes-base-addons/blob/master/CONTRIBUTING.md#addon-revisions).

**Comment by aayvazyan** [comment]
@shaneutt thanks for the review, done.

**Comment by joejulian** [comment]
@shaneutt I thought we'd all decided to only keep a single revision for this repo, specifically. The docs don't seem to reflect that. That _is_ what we decided, isn't it?

**Pull request merged**
