### PR TITLE
remove ambassador

### PR DESCRIPTION
**Pull request by joejulian**
**What type of PR is this?**

feature

**What this PR does/ why we need it**:

Ambassador failed its  evaluation and is no longer needed. Keeping it around  is only producing a maintenance burden.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
removed ambassador
```

**Checklist**

* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Review by alejandroEsc — APPROVED** [review]
lgtm

**Comment by alejandroEsc** [comment]
I wonder if we do not fix the panics about not finding the addon if other PRs will likewise fail. I do not think we have ever tested removing addons from kba.

**Comment by vespian** [comment]
@joejulian Let's please make sure next time to also start a discussion on Slack in the #sig-ksphere-networking channel so that all interested parties can chime in.

https://mesosphere.slack.com/archives/CMG6Y3C9X/p1620113214122900

**Review by GoelDeepak — APPROVED** [review]

**Comment by joejulian** [comment]
test-all

**Pull request merged**
