### PR TITLE
Remove the KUDO addon

### PR DESCRIPTION
**Pull request by nfnt**
As of https://github.com/mesosphere/kubeaddons/pull/698, KUDO will be deployed as part of 'kubeaddons' instead of an addon.

### CODE REVIEW

**Comment by shaneutt** [comment]
Please consider this blocked on the release of Konvoy 1.3 to reduce problems that can occur with dependencies with that version.

**Comment by alejandroEsc** [comment]
@shaneutt is this still blocked?

**Comment by shaneutt** [comment]
> @shaneutt is this still blocked?

When https://github.com/mesosphere/kubeaddons/pull/698 is corrected and merged and if it makes it into the Konvoy 1.3 release, we could consider this unblocked. Otherwise Konvoy 1.3 depends on the Kudo addon and this should hold until we've cut that release.

**Comment by shaneutt** [comment]
No longer blocked, Konvoy 1.3 no longer wants to deploy this by default.

**Pull request merged**
