### PR TITLE
traefik: remove requirement of a storage class

### PR DESCRIPTION
**Pull request by hectorj2f**
We don't need storage for traefik

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@hectorj2f  wonder why we added that in the first place? was it just a bulk update on all addons?

**Comment by hectorj2f** [comment]
@GoelDeepak honestly it seems to me it was a hack decision as you can see in the PR https://github.com/mesosphere/kubeaddons-configs/pull/207/files#diff-74a5bec821af9f2e0810c143abc9c059R11.

**Comment by hectorj2f** [comment]
I have a related PR against kommander-beta8 https://github.com/mesosphere/kubernetes-base-addons/pull/43, please have a look at the PR

**Comment by jaxesn** [comment]
This was Joe's comment on the original PR which added this. Is this no longer the case?

https://github.com/mesosphere/kubeaddons-configs/pull/207#discussion_r321247594

**Comment by hectorj2f** [comment]
@jaxesn This is optional for traefik chart to store ACME certificates, but we don't use it.

**Comment by hectorj2f** [comment]
I had a discussion with Sam I will block this PR and until a further discussion happens I will install a storage addon even if I don't need it in my case 😂

**Comment by joejulian** [comment]
Since a user _could_ enable acme and require a pvc but:
- We don't have any dynamic way of requiring a storageclass only when needed
- We don't have a way to add a requirement in cluster.yaml

Eventually I'd like us to be able do the former.

**Comment by hectorj2f** [comment]
In relation to this discussion, Jimmi proposed to disable traefik acme and use cert manager acme instead.

**Comment by jieyu** [comment]
+1 on using cert-manager ACME so that we can potentially use another ingress in the future.

**Comment by shaneutt** [comment]
@hectorj2f this has been waiting in `wip` for some time, is there anything we can do to help move this into a `ready` state? Do you need anything?

**Comment by hectorj2f** [comment]
@shaneutt To move it to higher priority or if anyone can pick this task and do it. I didn't have enough time to complete the requested and agreed changes.

**Comment by shaneutt** [comment]
> @shaneutt To move it to higher priority or if anyone can pick this task and do it. I didn't have enough time to complete the requested and agreed changes.

Understood, I will patch it.

**Comment by shaneutt** [comment]
The testing situation doesn't have good support for what we'd want here without greatly increasing the scope of this PR, as such I've created https://jira.mesosphere.com/browse/DCOS-63330 as a follow up to expand this and related test cases.

**Comment by GoelDeepak** [comment]
I have an idea of making it a little easy for the reviewers

Why don't we make two commits? 
1. Copy the old file and rename it according to the new version
2. make inline changes in the new file

That way it will be easier to see the diff and approve it

**Comment by alejandroEsc** [comment]
> @jaxesn This is optional for traefik chart to store ACME certificates, but we don't use it.

could we then have a note in the chart in case we ever decide to?

**Comment by jaxesn** [comment]
> I have an idea of making it a little easy for the reviewers
> 
> Why don't we make two commits?
> 
> 1. Copy the old file and rename it according to the new version
> 2. make inline changes in the new file
> 
> That way it will be easier to see the diff and approve it

I really like this idea.. I get worried with the PRs in this repo since they are full file changes, even tho maybe its only a version change.  Seems like its too easy to rubber stamp and miss something...  If this approach works, might be nice to distribute this out, or update the readme doc so others follow.

**Comment by shaneutt** [comment]
@GoelDeepak & @jaxesn that sounds good to me. My recent updates reflect that, and add documentation to cover it for future contributors.

Also I just wanted to mention again that [DCOS-62943](https://jira.mesosphere.com/browse/DCOS-62943) is the follow up we can work on to get revisions into a fully automated state in the future so that developers don't even need to bother with them.

**Comment by shaneutt** [comment]
> > @jaxesn This is optional for traefik chart to store ACME certificates, but we don't use it.
> 
> could we then have a note in the chart in case we ever decide to?

I would argue that this is the responsibility of the Helm chart to document so that we can make corrections to our addon if we decide to use additional features in the future, and this [is documented via the acme.persistence.enabled options in the upstream helm chart documentation](https://github.com/helm/charts/tree/master/stable/traefik).

Let me know what you think?

**Pull request merged**
